In [1]:
#Define Single and Multi-Dimensional Numpy Array

In [2]:
import numpy as np

In [3]:
list_1=[50,60,80,100,200,300,500,600]
list_1

[50, 60, 80, 100, 200, 300, 500, 600]

In [4]:
num_array=np.array(list_1)
num_array

array([ 50,  60,  80, 100, 200, 300, 500, 600])

In [5]:
type(num_array)

numpy.ndarray

In [6]:
m_maxrix=np.array([[3,7,9,3],[4,3,2,2]])
m_maxrix

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

In [7]:
 #Leverage numpy Built-in Methods and Functions

In [8]:
x=np.random.rand(20)
x

array([0.67222453, 0.61532105, 0.07957144, 0.88452583, 0.38120334,
       0.8000617 , 0.1440947 , 0.28566571, 0.78246402, 0.94102523,
       0.15736039, 0.24582642, 0.63474481, 0.27726193, 0.38030595,
       0.66110008, 0.85211871, 0.36015048, 0.77815949, 0.10534305])

In [9]:
x=np.random.rand(3,3)
x

array([[0.16116825, 0.43894256, 0.81342537],
       [0.01923534, 0.3748811 , 0.19140369],
       [0.88200681, 0.79734328, 0.16522277]])

In [10]:
x=np.random.randint(1,20)
x

16

In [11]:
x=np.random.randint(1,20,8)
x

array([14,  6,  3, 12, 11,  7, 19,  2])

In [12]:
x=np.arange(1,25)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [13]:
x=np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
x=np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
x=np.zeros((5,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
x=int(input())
y=np.random.randint(1,x,10)
y

 16


array([12, 10, 12, 11, 15, 11,  1, 11, 13,  9])

In [17]:
#perform Mathematical Operations in Numpy

In [18]:
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
y=np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
sum=x+y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
squared=x**2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [22]:
squared_root=np.sqrt(squared)
squared_root

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [23]:
a=np.exp(x)
a

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [24]:
x=np.array([5,7,20])
y=np.array([9,15,4])

z=np.sqrt(x**2 + y**2)
z

array([10.29563014, 16.55294536, 20.39607805])

In [25]:
#Perform Arrays Slicing and Indexing

In [26]:
my_nparr=np.array([3,5,6,2,8,10,20,50])
my_nparr

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [27]:
my_nparr[0]

3

In [28]:
my_nparr[-2]

20

In [29]:
my_nparr[1:5]

array([5, 6, 2, 8])

In [30]:
my_nparr[0:4]=7
my_nparr

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [31]:
matrix=np.random.randint(1,10,(4,4))
matrix

array([[1, 5, 8, 8],
       [9, 5, 8, 2],
       [2, 8, 2, 7],
       [6, 3, 8, 5]])

In [32]:
matrix[-1]

array([6, 3, 8, 5])

In [33]:
matrix[3]

array([6, 3, 8, 5])

In [34]:
matrix[1,3]

2

In [35]:
matrix[-1]=0
matrix

array([[1, 5, 8, 8],
       [9, 5, 8, 2],
       [2, 8, 2, 7],
       [0, 0, 0, 0]])

In [36]:
#Perform elements selection(Conditional)

In [37]:
matrix=np.random.randint(1,10,(5,5))
matrix

array([[5, 8, 8, 3, 7],
       [7, 2, 6, 7, 5],
       [1, 8, 3, 4, 3],
       [9, 3, 1, 8, 4],
       [7, 3, 1, 1, 3]])

In [38]:
new_matrix=matrix[matrix>5]
new_matrix

array([8, 8, 7, 7, 6, 7, 8, 9, 8, 7])

In [39]:
new_matrix=matrix[matrix%2==1]
new_matrix

array([5, 3, 7, 7, 7, 5, 1, 3, 3, 9, 3, 1, 7, 3, 1, 1, 3])

In [40]:
new_matrix=matrix[matrix%2==0]
new_matrix

array([8, 8, 2, 6, 8, 4, 8, 4])

In [41]:
x=np.array([[2,30,20,-2,-4],
           [3,4,40,-3,-2],
           [-3,4,-6,90,10],
           [25,45,34,22,12],
           [13,24,22,32,37]])
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [42]:
x[x<0]=0
x[x%2==1]=-2
x

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

In [43]:
#understand pandas fundamentals

In [44]:
import pandas as pd

In [45]:
bank_client_df=pd.DataFrame({'Bank Client ID':[101,201,301,401],
                            'Bank Client Name':['John','Steven','Rom','Sree'],
                            'Net Worth[$]':[5243,3541,4525,5645],
                            'Years with bank':[3,5,1,8]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth[$]  Years with bank
0             101             John          5243                3
1             201           Steven          3541                5
2             301              Rom          4525                1
3             401             Sree          5645                8

In [46]:
type(bank_client_df)

pandas.core.frame.DataFrame

In [47]:
bank_client_df.head(2)

Bank Client ID Bank Client Name  Net Worth[$]  Years with bank
0             101             John          5243                3
1             201           Steven          3541                5

In [48]:
bank_client_df.tail(2)

Bank Client ID Bank Client Name  Net Worth[$]  Years with bank
2             301              Rom          4525                1
3             401             Sree          5645                8

In [49]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40], 
                             'Number of stocks':[3, 4, 9]})
portfolio_df

stock ticker symbols  price per share [$]  Number of stocks
0                 AAPL                 3500                 3
1                 AMZN                  200                 4
2                    T                   40                 9

In [50]:
#To calculate the total value of portfolio including all the stocks

total_value=portfolio_df['price per share [$]']*portfolio_df['Number of stocks']
total_value.sum()

11660

In [51]:
#Pandas with HTML Data

In [52]:
retirement_df=pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_df[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

In [53]:
#Pandas Operations

In [54]:
bank_client_df=pd.DataFrame({'Bank Client ID':[101,201,301,401],
                            'Bank Client Name':['John','Steven','Rom','Sree'],
                            'Net Worth[$]':[5243,3541,4525,5645],
                            'Years with bank':[3,5,1,8]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth[$]  Years with bank
0             101             John          5243                3
1             201           Steven          3541                5
2             301              Rom          4525                1
3             401             Sree          5645                8

In [55]:
loyal_df=bank_client_df[bank_client_df['Years with bank']>=5]
loyal_df

Bank Client ID Bank Client Name  Net Worth[$]  Years with bank
1             201           Steven          3541                5
3             401             Sree          5645                8

In [56]:
del bank_client_df['Bank Client ID']
bank_client_df

Bank Client Name  Net Worth[$]  Years with bank
0             John          5243                3
1           Steven          3541                5
2              Rom          4525                1
3             Sree          5645                8

In [57]:
#Only select high network individuals with minimum of $5000
high_network_df=bank_client_df[bank_client_df['Net Worth[$]']>=5000]
high_network_df

Bank Client Name  Net Worth[$]  Years with bank
0             John          5243                3
3             Sree          5645                8

In [58]:
#Combined network of all customers with 5000+ Networth
high_network_df['Net Worth[$]'].sum()

10888

In [59]:
#Pandas with functions

In [60]:
bank_client_df=pd.DataFrame({'Bank Client ID':[101,201,301,401],
                            'Bank Client Name':['John','Steven','Rom','Sree'],
                            'Net Worth[$]':[5243,3541,4525,5645],
                            'Years with bank':[3,5,1,8]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth[$]  Years with bank
0             101             John          5243                3
1             201           Steven          3541                5
2             301              Rom          4525                1
3             401             Sree          5645                8

In [61]:
bank_client_df['Bank Client Name'].apply(len)

0    4
1    6
2    3
3    4
Name: Bank Client Name, dtype: int64

In [62]:
def network_update(balance):
    return balance*1.2

In [63]:
bank_client_df['Net Worth[$]'].apply(network_update)

0    6291.6
1    4249.2
2    5430.0
3    6774.0
Name: Net Worth[$], dtype: float64

In [64]:
def triple_network(balance):
    return balance*3+200

In [65]:
results=bank_client_df['Net Worth[$]'].apply(triple_network)
results

0    15929
1    10823
2    13775
3    17135
Name: Net Worth[$], dtype: int64

In [66]:
results.sum()

57662

In [67]:
#Perform sorting and ordering in pandas

In [68]:
bank_client_df=pd.DataFrame({'Bank Client ID':[101,201,301,401],
                            'Bank Client Name':['John','Steven','Rom','Sree'],
                            'Net Worth[$]':[5243,3541,4525,5645],
                            'Years with bank':[3,5,1,8]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth[$]  Years with bank
0             101             John          5243                3
1             201           Steven          3541                5
2             301              Rom          4525                1
3             401             Sree          5645                8

In [69]:
bank_client_df.sort_values(by = 'Years with bank',inplace=True)

In [70]:
bank_client_df

Bank Client ID Bank Client Name  Net Worth[$]  Years with bank
2             301              Rom          4525                1
0             101             John          5243                3
1             201           Steven          3541                5
3             401             Sree          5645                8

In [71]:
#Perform concatenating and merging with pandas

In [72]:
df1=pd.DataFrame({'A':['A0','A1','A2','A3'],
                 'B':['B0','B1','B2','B3'],
                 'C':['C0','C1','C2','C3'],
                 'D':['D0','D1','D2','D3']},
                index=[0,1,2,3])
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [73]:
df2=pd.DataFrame({'A':['A4','A5','A6','A7'],
                 'B':['B4','B5','B6','B7'],
                 'C':['C4','C5','C6','C7'],
                 'D':['D4','D5','D6','D7']},
                index=[4,5,6,7])
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [74]:
df3=pd.DataFrame({'A':['A8','A9','A10','A11'],
                 'B':['B8','B9','B10','B11'],
                 'C':['C8','C9','C10','C11'],
                 'D':['D8','D9','D10','D11']},
                index=[8,9,10,11])
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [75]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [76]:
raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1

Bank Client ID First Name Last Name
0              1      Nancy       Rob
1              2       Alex       Ali
2              3       Shep    George
3              4        Max     Mitch
4              5      Allen     Steve

In [77]:
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2

Bank Client ID First Name  Last Name
0              6       Bill  Christian
1              7       Dina         Mo
2              8      Sarah      Steve
3              9    Heather        Bob
4             10      Holly   Michelle

In [78]:
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary

Bank Client ID  Annual Salary [$/year]
0              1                   25000
1              2                   35000
2              3                   45000
3              4                   48000
4              5                   49000
5              6                   32000
6              7                   33000
7              8                   34000
8              9                   23000
9             10                   22000

In [79]:
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all

Bank Client ID First Name  Last Name
0              1      Nancy        Rob
1              2       Alex        Ali
2              3       Shep     George
3              4        Max      Mitch
4              5      Allen      Steve
0              6       Bill  Christian
1              7       Dina         Mo
2              8      Sarah      Steve
3              9    Heather        Bob
4             10      Holly   Michelle

In [80]:
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all

Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000

In [81]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

Bank Client ID First Name Last Name  Annual Salary [$/year]
0             11         Ry       Aly                    1000

In [82]:
new_df = pd.concat([bank_df_all, new_client_df])
new_df

Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000
0             11         Ry        Aly                    1000